baseURL = 'https://localhost/'
locale = 'en-us'
title = 'Error Code Hub'
theme = 'blowfish'

[menu]

  [[menu.main]]
    name = 'Devices'
    url = '/devices/'
    weight = 10

[params]
  enableBlocks = true
  showDate = false
  showReadingTime = false
  showAuthor = false
  showSummary = false
